name: Hoarder
version: "0.21.0-v1"
slug: hoarder
codenotary: info@fabiogaravini.dev
description: bookmark-everything app with a touch of AI for the data hoarders out there
url: https://hoarder.app/
webui: http://[HOST]:[PORT:3000]
arch:
  - aarch64
  - amd64
init: false
hassio_api: true
map:
  - type: share
    read_only: false
  - type: ssl
backup: cold
backup_exclude:
  - "**/logs"
schema:
  TZ: str?
  DISABLE_SIGNUPS: bool
  NEXTAUTH_SECRET: password
  MAX_ASSET_SIZE_MB: int?
  NEXTAUTH_URL: url?
  OCR_LANGS: str?
  OCR_CONFIDENCE_THRESHOLD: int(0,100)?
  OPENAI_API_KEY: password?
  OPENAI_BASE_URL: url?
  OLLAMA_BASE_URL: url?
  INFERENCE_TEXT_MODEL: str?
  INFERENCE_IMAGE_MODEL: str?
  EMBEDDING_TEXT_MODEL: str?
  INFERENCE_CONTEXT_LENGTH: int(0,)?
  INFERENCE_LANG: str?
  INFERENCE_JOB_TIMEOUT_SEC: int(0,)?
  CRAWLER_DOWNLOAD_BANNER_IMAGE: bool?
  CRAWLER_STORE_SCREENSHOT: bool?
  CRAWLER_FULL_PAGE_SCREENSHOT: bool?
  CRAWLER_FULL_PAGE_ARCHIVE: bool?
  CRAWLER_JOB_TIMEOUT_SEC: int(0,)?
  CRAWLER_NAVIGATE_TIMEOUT_SEC: int(0,)?
  CRAWLER_VIDEO_DOWNLOAD: bool?
  CRAWLER_VIDEO_DOWNLOAD_MAX_SIZE: str?
  CRAWLER_VIDEO_DOWNLOAD_TIMEOUT_SEC: int(0,)?
  CRAWLER_ENABLE_ADBLOCKER: bool?
options:
  TZ: Etc/UTC
  DISABLE_SIGNUPS: false
  NEXTAUTH_SECRET: "jnE2An0WyIKZvO+WgKJrn8WPW+c3DzV+c9ntBp8CdobTOmpJ"
  MAX_ASSET_SIZE_MB: 4
ports:
  3000/tcp: 3011
ports_description:
  3000/tcp: Web UI
image: fabioogaravini/hassio-{arch}-hoarder