name: OpenCloud
version: 5.0.2
slug: opencloud
description: "file sharing platform: Secure, simple and reliable"
url: https://opencloud.eu
webui: "[PROTO:ssl]://[HOST]:[PORT:8080]"
arch:
  - aarch64
  - amd64
init: false
hassio_api: true
map:
  - type: addon_config
    read_only: false
  - type: share
    read_only: false
  - type: ssl
backup: cold
backup_exclude:
  - "**/logs"
schema:
  OC_LOG_LEVEL: list(panic|fatal|error|warn|info|debug|trace)
  OC_URL: str
  OC_BASE_DATA_PATH: str
  TZ: str?
  ssl: bool
  certfile: str?
  keyfile: str?
  OC_DEFAULT_LANGUAGE: str
  OC_SHARING_PUBLIC_SHARE_MUST_HAVE_PASSWORD: bool
  OC_SHARING_PUBLIC_WRITEABLE_SHARE_MUST_HAVE_PASSWORD: bool
  NOTIFICATIONS_SMTP_HOST: str?
  NOTIFICATIONS_SMTP_PORT: int(0,65535)?
  NOTIFICATIONS_SMTP_SENDER: str?
  NOTIFICATIONS_SMTP_USERNAME: str?
  NOTIFICATIONS_SMTP_PASSWORD: password?
  NOTIFICATIONS_SMTP_INSECURE: bool?
  NOTIFICATIONS_SMTP_AUTHENTICATION: str?
  NOTIFICATIONS_SMTP_ENCRYPTION: str?
options:
  OC_LOG_LEVEL: warn
  OC_BASE_DATA_PATH: /share/opencloud
  TZ: Etc/UTC
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  OC_DEFAULT_LANGUAGE: en
  OC_SHARING_PUBLIC_SHARE_MUST_HAVE_PASSWORD: true
  OC_SHARING_PUBLIC_WRITEABLE_SHARE_MUST_HAVE_PASSWORD: true
ports:
  8080/tcp: 9200
ports_description:
  8080/tcp: OpenCloud UI
image: fabioogaravini/hassio-opencloud
