name: HabitSync
version: 0.18.1-v1
slug: habitsync
description: habit tracking platform with social features
url: https://github.com/jofoerster/habitsync
webui: "[PROTO:ssl]://[HOST]:[PORT:8080]"
arch:
  - aarch64
  - amd64
init: false
hassio_api: true
map:
  - type: data
    read_only: false
  - type: ssl
backup: cold
backup_exclude:
  - "**/logs"
schema:
  users:
    - user: str
      password: password
  TZ: str?
  ssl: bool
  certfile: str?
  keyfile: str?
  BASE_URL: str
  PAGE_CHALLENGES_VISIBLE: bool?
  SPRING_MAIL_ENABLED: bool?
  SPRING_MAIL_HOST: str?
  SPRING_MAIL_USERNAME: str?
  SPRING_MAIL_PASSWORD: password?
  SPRING_MAIL_PORT: int(0,65535)?
  APPRISE_API_URL: str?
  JWT_SECRET: password?
  PUID: int(0,)
  PGID: int(0,)
  env_vars:
    - key: match(^[A-Za-z0-9_-]+$)
      value: str
options:
  TZ: Etc/UTC
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  SPRING_MAIL_ENABLED: false
  PUID: 0
  PGID: 0
  env_vars: []
ports:
  8080/tcp: 6842
ports_description:
  8080/tcp: Web UI
image: fabioogaravini/hassio-habitsync
