name: n8n
version: 2.9.1
slug: n8n
description: Flexible AI workflow automation
url: https://n8n.io
webui: "[PROTO:ssl]://[HOST]:[PORT:5678]"
hassio_api: true
arch:
  - aarch64
  - amd64
init: false
map:
  - type: addon_config
    read_only: false
  - type: share
    read_only: false
  - type: media
    read_only: false
  - type: ssl
backup: cold
backup_exclude:
  - "**/logs"
schema:
  N8N_LOG_LEVEL: list(error|warn|info|debug)
  TZ: str?
  GENERIC_TIMEZONE: str?
  ssl: bool
  certfile: str?
  keyfile: str?
  N8N_HOST: str?
  N8N_PATH: str?
  WEBHOOK_URL: str?
  clean_redis: bool?
  env_vars:
    - key: match(^[A-Za-z0-9_-]+$)
      value: str
options:
  N8N_LOG_LEVEL: info
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  env_vars: []
ports:
  5678/tcp: 5678
ports_description:
  5678/tcp: Web UI
image: fabioogaravini/hassio-n8n
