name: ownCloud
version: 10.16.0
slug: owncloud
description: content collaboration platform
url: https://owncloud.com/
webui: "[PROTO:ssl]://[HOST]:[PORT:8080]"
arch:
  - aarch64
  - amd64
init: false
hassio_api: true
map:
  - type: share
    read_only: false
  - type: ssl
backup: cold
backup_exclude:
  - "**/logs"
schema:
  TZ: str?
  ssl: bool
  certfile: str?
  keyfile: str?
  OWNCLOUD_VOLUME_FILES: str
  OWNCLOUD_ADMIN_USERNAME: str
  OWNCLOUD_ADMIN_PASSWORD: password
  OWNCLOUD_TRUSTED_DOMAINS: str?
  OWNCLOUD_TRUSTED_PROXIES: str?
  OWNCLOUD_DOMAIN: str?
  OWNCLOUD_OVERWRITE_CLI_URL: str?
  OWNCLOUD_OVERWRITE_HOST: str?
  OWNCLOUD_OVERWRITE_PROTOCOL: str?
  OWNCLOUD_DEFAULT_LANGUAGE: str?
  OWNCLOUD_MAIL_DOMAIN: str?
  OWNCLOUD_MAIL_FROM_ADDRESS: str?
  OWNCLOUD_MAIL_SMTP_MODE: str?
  OWNCLOUD_MAIL_SMTP_HOST: str?
  OWNCLOUD_MAIL_SMTP_PORT: int(0,65535)?
  OWNCLOUD_MAIL_SMTP_SECURE: str?
  OWNCLOUD_MAIL_SMTP_AUTH: bool?
  OWNCLOUD_MAIL_SMTP_AUTH_TYPE: str?
  OWNCLOUD_MAIL_SMTP_NAME: str?
  OWNCLOUD_MAIL_SMTP_PASSWORD: password?
  OWNCLOUD_UPDATE_CHECKER: bool
options:
  TZ: Etc/UTC
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  OWNCLOUD_VOLUME_FILES: /share/owncloud
  OWNCLOUD_TRUSTED_PROXIES: 127.0.0.1
  OWNCLOUD_UPDATE_CHECKER: false
ports:
  8000/tcp: 8080
ports_description:
  8000/tcp: Web UI
image: fabioogaravini/hassio-owncloud
