name: Calibre Web
version: 0.6.25-v3
slug: calibre-web
description: Calibre ebook reader
url: https://github.com/janeczku/calibre-web
ingress: true
ingress_port: 8080
ingress_stream: true
panel_title: Calibre Web
panel_icon: mdi:library
arch:
  - aarch64
  - amd64
init: false
map:
  - type: addon_config
    read_only: false
  - type: share
    read_only: false
  - type: media
    read_only: false
schema:
  ssl: bool
  certfile: str?
  keyfile: str?
  ingress_user: str?
  PUID: int(0,)
  PGID: int(0,)
  TZ: str?
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  ingress_user: admin
  PUID: 1000
  PGID: 1000
  TZ: Etc/UTC
ports:
  8080/tcp: null
ports_description:
  8080/tcp: Web UI (not needed for Ingress)
image: fabioogaravini/hassio-calibre-web
