name: Cloudflared
version: 2025.10.1
slug: cloudflared
codenotary: info@fabiogaravini.dev
description: Cloudflare tunneling and Zero Trust service
arch:
  - aarch64
  - amd64
  - armv7
init: false
map:
  - type: addon_config
    read_only: false
schema:
  token: password?
image: fabioogaravini/hassio-cloudflared
