name: Cloudflared
version: 2026.1.1
slug: cloudflared
description: Cloudflare tunneling and Zero Trust service
arch:
  - aarch64
  - amd64
init: false
map:
  - type: addon_config
    read_only: false
schema:
  token: password?
image: fabioogaravini/hassio-cloudflared
