name: Cloudflared
version: 2026.1.2
slug: cloudflared
description: Cloudflare tunneling and Zero Trust service
arch:
  - aarch64
  - amd64
init: false
map:
  - type: addon_config
    read_only: false
schema:
  TUNNEL_NAME: str
  token: password?
  warp-routing: bool
  network_routings:
    - str
  originRequest:
    noTLSVerify: bool
    connectTimeout: str
    disableChunkedEncoding: bool
  ingress:
    - hostname: str?
      path: str?
      service: str
options:
  TUNNEL_NAME: HomeAssistant
  warp-routing: true
  network_routings: []
  originRequest:
    noTLSVerify: false
    connectTimeout: 30s
    disableChunkedEncoding: false
  ingress: []
image: fabioogaravini/hassio-cloudflared
