---
name: Grimoire
version: 0.4.4
slug: grimoire
codenotary: info@fabiogaravini.dev
description: Bookmark manager for the wizards ðŸ§™
url: https://github.com/goniszewski/grimoire
webui: "[PROTO:ssl]://[HOST]:[PORT:5173]"
arch:
  - aarch64
  - amd64
init: false
map:
  - type: addon_config
    read_only: false
    path: /app/data
  - type: data
    read_only: false
  - type: ssl
    read_only: false
backup: cold
schema:
  PUBLIC_SIGNUP_DISABLED: bool
  ssl: bool
  certfile: str?
  keyfile: str?
  PUBLIC_ORIGIN: str?
options:
  PUBLIC_SIGNUP_DISABLED: false
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
ports:
  5173/tcp: 5173
ports_description:
  5173/tcp: Grimoire
#image: fabioogaravini/hassio-grimoire
