name: Collabora CODE
version: 25.04.8.1.1
slug: collabora_code
description: Online Office suite image suitable for home use
url: https://www.collaboraoffice.com
arch:
  - aarch64
  - amd64
init: false
ports:
  9980/tcp: 9980
ports_description:
  9980/tcp: HTTP
image: collabora/code
