name: Monica
version: 5.0.0-beta.5-v2
slug: monica
description: personal relationship management system, that lets you document your life
url: https://github.com/monicahq/monica
webui: "http://[HOST]:[PORT:80]"
arch:
  - aarch64
  - amd64
init: false
map:
  - type: addon_config
    read_only: false
    path: /var/www/html/storage
  - type: data
    read_only: false
  - type: ssl
    read_only: false
backup: cold
ports:
  80/tcp: 8080
ports_description:
  80/tcp: Monica
image: fabioogaravini/hassio-monica
